#!/bin/bash

dir=.

if [ -n "$1" ]
then
    dir=$1
fi

list=$(find $dir -name '*.log')

if [$list = ""]
then
    echo "No logs found"
    exit 1
fi


for file in $list 
do
	sed -i '' '/password/d' $file
done
tar -zcvf archive.tar.gz $list
rm $list

